<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones. 

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage. 


Therefore if we can determine if the first stage will land, we can determine the cost of a launch. 

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

In [1]:
!pip install sqlalchemy==1.3.9

Collecting sqlalchemy==1.3.9
  Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)
                                              0.0/6.0 MB ? eta -:--:--
     --                                       0.4/6.0 MB 12.6 MB/s eta 0:00:01
     -------                                  1.0/6.0 MB 13.3 MB/s eta 0:00:01
     -------                                  1.0/6.0 MB 13.3 MB/s eta 0:00:01
     -------                                  1.0/6.0 MB 13.3 MB/s eta 0:00:01
     -------                                  1.2/6.0 MB 5.4 MB/s eta 0:00:01
     ------------                             1.9/6.0 MB 7.1 MB/s eta 0:00:01
     --------------                           2.1/6.0 MB 7.4 MB/s eta 0:00:01
     --------------                           2.1/6.0 MB 7.4 MB/s eta 0:00:01
     ---------------                          2.3/6.0 MB 6.0 MB/s eta 0:00:01
     --------------------                     3.0/6.0 MB 6.8 MB/s eta 0:00:01
     ---------------------                    3.1/6.0 MB 6.9 MB/s eta 0:00:01
     ----------------------                   3.3/6.0 MB 6.2 MB/s eta 0:00:01
     ---------------------------              4.0/6.0 MB 7.0 MB/s eta 0:00:01
     ----------------------------             4.2/6.0 MB 7.0 MB/s eta 0:00:01
     ----------------------------             4.2/6.0 MB 7.0 MB/s eta 0:00:01
     ---------------------------------        5.0/6.0 MB 6.9 MB/s eta 0:00:01
     --------------------------------------   5.8/6.0 MB 7.5 MB/s eta 0:00:01
     ---------------------------------------- 6.0/6.0 MB 7.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py): started
  Building wheel for sqlalchemy (setup.py): finished with status 'done'
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.9-cp311-cp311-win_amd64.whl size=1142948 sha256=700715c18156ef8b7084a9ebed6f6830bb4d9d392f44789462debb25f4c75d2b
  Stored in directory: c:\users\benib\appdata\local\pip\cache\wheels\3a\7c\1e\12404784a68083eb969f877a1808a1847bab897684b56ddc55
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-1.3.9

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [2]:
#Please uncomment and execute the code below if you are working locally.

!pip install ipython-sql

Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Collecting prettytable (from ipython-sql)
  Downloading prettytable-3.10.0-py3-none-any.whl (28 kB)
Requirement already satisfied: ipython in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from ipython-sql) (8.22.1)
Collecting sqlalchemy>=2.0 (from ipython-sql)
  Downloading SQLAlchemy-2.0.27-cp311-cp311-win_amd64.whl (2.1 MB)
                                              0.0/2.1 MB ? eta -:--:--
     --------------------                     1.1/2.1 MB 22.4 MB/s eta 0:00:01
     ---------------------------------------- 2.1/2.1 MB 26.4 MB/s eta 0:00:00
Collecting sqlparse (from ipython-sql)
  Downloading sqlparse-0.4.4-py3-none-any.whl (41 kB)
                                              0.0/41.2 kB ? eta -:--:--
     ---------------------------------------- 41.2/41.2 kB ? eta 0:00:00
Requirement already satisfied: six in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from ipython-sql) (1.16.0)
Collecting ipython-genutils (from ipython-sql)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy>=2.0->ipython-sql)
  Downloading typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Collecting greenlet!=0.4.17 (from sqlalchemy>=2.0->ipython-sql)
  Downloading greenlet-3.0.3-cp311-cp311-win_amd64.whl (292 kB)
                                              0.0/292.8 kB ? eta -:--:--
     ---------------------------------------- 292.8/292.8 kB ? eta 0:00:00
Requirement already satisfied: decorator in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from ipython->ipython-sql) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from ipython->ipython-sql) (2.17.2)
Requirement already satisfied: stack-data in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from ipython->ipython-sql) (5.14.1)
Requirement already satisfied: colorama in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from prettytable->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing>=1.2.0 in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from stack-data->ipython->ipython-sql) (2.4.1)
Requirement already satisfied: pure-eval in c:\users\benib\appdata\local\programs\python\python311\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Installing collected packages: ipython-genutils, typing-extensions, sqlparse, prettytable, greenlet, sqlalchemy, ipython-sql
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.5.0
    Uninstalling typing_extensions-4.5.0:
      Successfully uninstalled typing_extensions-4.5.0
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.3.9
    Uninstalling SQLAlchemy-1.3.9:
      Successfully uninstalled SQLAlchemy-1.3.9
Successfully installed greenlet-3.0.3 ipython-genutils-0.2.0 ipython-sql-0.5.0 prettytable-3.10.0 sqlalchemy-2.0.27 sqlparse-0.4.4 typing-extensions-4.10.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.13.0 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.10.0 which is incompatible.

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
%load_ext sql

In [4]:
import csv, sqlite3

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [ ]:
!pip install -q pandas==1.1.5

In [5]:
%sql sqlite:///my_data1.db

In [6]:
import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

101

**Note:This below code is added to remove blank rows from table**

In [7]:
%sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

 * sqlite:///my_data1.db
Done.

[]

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
   For Example "Landing_Outcome"**

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [10]:
cur.execute("SELECT DISTINCT(Launch_Site) FROM SPACEXTABLE").fetchall()

[('CCAFS LC-40',), ('VAFB SLC-4E',), ('KSC LC-39A',), ('CCAFS SLC-40',)]


### Task 2


#####  Display 5 records where launch sites begin with the string 'CCA'

In [11]:
cur.execute("SELECT * FROM SPACEXTABLE WHERE Launch_Site LIKE 'CCA%'").fetchall()

[('2010-06-04',
  '18:45:00',
  'F9 v1.0  B0003',
  'CCAFS LC-40',
  'Dragon Spacecraft Qualification Unit',
  0,
  'LEO',
  'SpaceX',
  'Success',
  'Failure (parachute)'),
 ('2010-12-08',
  '15:43:00',
  'F9 v1.0  B0004',
  'CCAFS LC-40',
  'Dragon demo flight C1, two CubeSats, barrel of Brouere cheese',
  0,
  'LEO (ISS)',
  'NASA (COTS) NRO',
  'Success',
  'Failure (parachute)'),
 ('2012-05-22',
  '7:44:00',
  'F9 v1.0  B0005',
  'CCAFS LC-40',
  'Dragon demo flight C2',
  525,
  'LEO (ISS)',
  'NASA (COTS)',
  'Success',
  'No attempt'),
 ('2012-10-08',
  '0:35:00',
  'F9 v1.0  B0006',
  'CCAFS LC-40',
  'SpaceX CRS-1',
  500,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'),
 ('2013-03-01',
  '15:10:00',
  'F9 v1.0  B0007',
  'CCAFS LC-40',
  'SpaceX CRS-2',
  677,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'),
 ('2013-12-03',
  '22:41:00',
  'F9 v1.1',
  'CCAFS LC-40',
  'SES-8',
  3170,
  'GTO',
  'SES',
  'Success',
  'No attempt'),
 ('2014-01-06',
  '22:06:00',
  'F9 v1.1',
  'CCAFS LC-40',
  'Thaicom 6',
  3325,
  'GTO',
  'Thaicom',
  'Success',
  'No attempt'),
 ('2014-04-18',
  '19:25:00',
  'F9 v1.1',
  'CCAFS LC-40',
  'SpaceX CRS-3',
  2296,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Controlled (ocean)'),
 ('2014-07-14',
  '15:15:00',
  'F9 v1.1',
  'CCAFS LC-40',
  'OG2 Mission 1  6 Orbcomm-OG2 satellites',
  1316,
  'LEO',
  'Orbcomm',
  'Success',
  'Controlled (ocean)'),
 ('2014-08-05',
  '8:00:00',
  'F9 v1.1',
  'CCAFS LC-40',
  'AsiaSat 8',
  4535,
  'GTO',
  'AsiaSat',
  'Success',
  'No attempt'),
 ('2014-09-07',
  '5:00:00',
  'F9 v1.1 B1011',
  'CCAFS LC-40',
  'AsiaSat 6',
  4428,
  'GTO',
  'AsiaSat',
  'Success',
  'No attempt'),
 ('2014-09-21',
  '5:52:00',
  'F9 v1.1 B1010',
  'CCAFS LC-40',
  'SpaceX CRS-4',
  2216,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Uncontrolled (ocean)'),
 ('2015-01-10',
  '9:47:00',
  'F9 v1.1 B1012',
  'CCAFS LC-40',
  'SpaceX CRS-5',
  2395,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Failure (drone ship)'),
 ('2015-02-11',
  '23:03:00',
  'F9 v1.1 B1013',
  'CCAFS LC-40',
  'DSCOVR',
  570,
  'HEO',
  'U.S. Air Force NASA NOAA',
  'Success',
  'Controlled (ocean)'),
 ('2015-03-02',
  '3:50:00',
  'F9 v1.1 B1014',
  'CCAFS LC-40',
  'ABS-3A Eutelsat 115 West B',
  4159,
  'GTO',
  'ABS Eutelsat',
  'Success',
  'No attempt'),
 ('2015-04-14',
  '20:10:00',
  'F9 v1.1 B1015',
  'CCAFS LC-40',
  'SpaceX CRS-6',
  1898,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Failure (drone ship)'),
 ('2015-04-27',
  '23:03:00',
  'F9 v1.1 B1016',
  'CCAFS LC-40',
  'Turkmen 52 / MonacoSAT',
  4707,
  'GTO',
  'Turkmenistan National Space Agency',
  'Success',
  'No attempt'),
 ('2015-06-28',
  '14:21:00',
  'F9 v1.1 B1018',
  'CCAFS LC-40',
  'SpaceX CRS-7',
  1952,
  'LEO (ISS)',
  'NASA (CRS)',
  'Failure (in flight)',
  'Precluded (drone ship)'),
 ('2015-12-22',
  '1:29:00',
  'F9 FT B1019',
  'CCAFS LC-40',
  'OG2 Mission 2  11 Orbcomm-OG2 satellites',
  2034,
  'LEO',
  'Orbcomm',
  'Success',
  'Success (ground pad)'),
 ('2016-03-04',
  '23:35:00',
  'F9 FT B1020',
  'CCAFS LC-40',
  'SES-9',
  5271,
  'GTO',
  'SES',
  'Success',
  'Failure (drone ship)'),
 ('2016-04-08',
  '20:43:00',
  'F9 FT B1021.1',
  'CCAFS LC-40',
  'SpaceX CRS-8',
  3136,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (drone ship)'),
 ('2016-05-06',
  '5:21:00',
  'F9 FT B1022',
  'CCAFS LC-40',
  'JCSAT-14',
  4696,
  'GTO',
  'SKY Perfect JSAT Group',
  'Success',
  'Success (drone ship)'),
 ('2016-05-27',
  '21:39:00',
  'F9 FT B1023.1',
  'CCAFS LC-40',
  'Thaicom 8',
  3100,
  'GTO',
  'Thaicom',
  'Success',
  'Success (drone ship)'),
 ('2016-06-15',
  '14:29:00',
  'F9 FT B1024',
  'CCAFS LC-40',
  'ABS-2A Eutelsat 117 West B',
  3600,
  'GTO',
  'ABS Eutelsat',
  'Success',
  'Failure (drone ship)'),
 ('2016-07-18',
  '4:45:00',
  'F9 FT B1025.1',
  'CCAFS LC-40',
  'SpaceX CRS-9',
  2257,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (ground pad)'),
 ('2016-08-14',
  '5:26:00',
  'F9 FT B1026',
  'CCAFS LC-40',
  'JCSAT-16',
  4600,
  'GTO',
  'SKY Perfect JSAT Group',
  'Success',
  'Success (drone ship)'),
 ('2017-12-15',
  '15:36:00',
  'F9 FT  B1035.2',
  'CCAFS SLC-40',
  'SpaceX CRS-13',
  2205,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (ground pad)'),
 ('2018-01-08',
  '1:00:00',
  'F9 B4 B1043.1',
  'CCAFS SLC-40',
  'Zuma',
  5000,
  'LEO',
  'Northrop Grumman',
  'Success (payload status unclear)',
  'Success (ground pad)'),
 ('2018-01-31',
  '21:25:00',
  'F9 FT  B1032.2',
  'CCAFS SLC-40',
  'GovSat-1 / SES-16',
  4230,
  'GTO',
  'SES',
  'Success',
  'Controlled (ocean)'),
 ('2018-03-06',
  '5:33:00',
  'F9 B4 B1044',
  'CCAFS SLC-40',
  'Hispasat 30W-6  PODSat',
  6092,
  'GTO',
  'Hispasat  NovaWurks',
  'Success',
  'No attempt'),
 ('2018-04-02',
  '20:30:00',
  'F9 B4  B1039.2',
  'CCAFS SLC-40',
  'SpaceX CRS-14',
  2647,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'),
 ('2018-04-18',
  '22:51:00',
  'F9 B4 B1045.1',
  'CCAFS SLC-40',
  'Transiting Exoplanet Survey Satellite (TESS)',
  362,
  'HEO',
  'NASA (LSP)',
  'Success',
  'Success (drone ship)'),
 ('2018-06-04',
  '4:45:00',
  'F9 B4  B1040.2',
  'CCAFS SLC-40',
  'SES-12',
  5384,
  'GTO',
  'SES',
  'Success',
  'No attempt'),
 ('2018-06-29',
  '9:42:00',
  'F9 B4 B1045.2',
  'CCAFS SLC-40',
  'SpaceX CRS-15',
  2697,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'),
 ('2018-07-22',
  '5:50:00',
  'F9 B5B1047.1',
  'CCAFS SLC-40',
  'Telstar 19V',
  7075,
  'GTO',
  'Telesat',
  'Success',
  'Success'),
 ('2018-08-07',
  '5:18:00',
  'F9 B5 B1046.2',
  'CCAFS SLC-40',
  'Merah Putih ',
  5800,
  'GTO',
  'Telkom Indonesia',
  'Success',
  'Success'),
 ('2018-09-10',
  '4:45:00',
  'F9 B5B1049.1',
  'CCAFS SLC-40',
  'Telstar 18V / Apstar-5C',
  7060,
  'GTO',
  'Telesat',
  'Success',
  'Success'),
 ('2018-12-05',
  '18:16:00',
  'F9 B5B1050',
  'CCAFS SLC-40',
  'SpaceX CRS-16',
  2500,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Failure'),
 ('2018-12-23',
  '13:51:00',
  'F9 B5B1054',
  'CCAFS SLC-40',
  'GPS III-01 ',
  4400,
  'MEO',
  'USAF',
  'Success ',
  'No attempt'),
 ('2019-02-22',
  '1:45:00',
  'F9 B5 B1048.3',
  'CCAFS SLC-40',
  'Nusantara Satu, Beresheet Moon lander, S5',
  4850,
  'GTO',
  'PSN, SpaceIL / IAI',
  'Success',
  'Success'),
 ('2019-05-04',
  '6:48:00',
  'F9 B5B1056.1 ',
  'CCAFS SLC-40',
  'SpaceX CRS-17, Starlink v0.9',
  2495,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success'),
 ('2019-05-24',
  '2:30:00',
  'F9 B5 B1049.3',
  'CCAFS SLC-40',
  'Starlink v0.9, RADARSAT Constellation',
  13620,
  'LEO',
  'SpaceX',
  'Success',
  'Success'),
 ('2019-07-25',
  '22:01:00',
  'F9 B5 B1056.2 ',
  'CCAFS SLC-40',
  'SpaceX CRS-18, AMOS-17 ',
  2268,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success'),
 ('2019-08-06',
  '23:23:00',
  'F9 B5 B1047.3 ',
  'CCAFS SLC-40',
  'AMOS-17, Starlink 1 v1.0 ',
  6500,
  'GTO',
  'Spacecom',
  'Success',
  'No attempt '),
 ('2019-11-11',
  '14:56:00',
  'F9 B5 B1048.4',
  'CCAFS SLC-40',
  'Starlink 1 v1.0, SpaceX CRS-19 ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'),
 ('2019-12-05',
  '17:29:00',
  'F9 B5B1059.1',
  'CCAFS SLC-40',
  'SpaceX CRS-19, JCSat-18 / Kacific 1 ',
  2617,
  'LEO (ISS)',
  'NASA (CRS), Kacific 1',
  'Success',
  'Success'),
 ('2019-12-17',
  '0:10:00',
  'F9 B5 B1056.3 ',
  'CCAFS SLC-40',
  'JCSat-18 / Kacific 1, Starlink 2 v1.0 ',
  6956,
  'GTO',
  'Sky Perfect JSAT, Kacific 1',
  'Success',
  'Success'),
 ('2020-01-07',
  '2:33:00',
  'F9 B5 B1049.4',
  'CCAFS SLC-40',
  'Starlink 2 v1.0, Crew Dragon in-flight abort test ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'),
 ('2020-01-29',
  '14:07:00',
  'F9 B5 B1051.3',
  'CCAFS SLC-40',
  'Starlink 3 v1.0, Starlink 4 v1.0 ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'),
 ('2020-02-17',
  '15:05:00',
  'F9 B5 B1056.4',
  'CCAFS SLC-40',
  'Starlink 4 v1.0, SpaceX CRS-20',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Failure'),
 ('2020-03-07',
  '4:50:00',
  'F9 B5 B1059.2',
  'CCAFS SLC-40',
  'SpaceX CRS-20, Starlink 5 v1.0 ',
  1977,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success'),
 ('2020-06-04',
  '1:25:00',
  'F9 B5 B1049.5',
  'CCAFS SLC-40',
  'Starlink 7 v1.0, Starlink 8 v1.0',
  15600,
  'LEO',
  'SpaceX, Planet Labs',
  'Success',
  'Success'),
 ('2020-06-13',
  '9:21:00',
  'F9 B5 B1059.3',
  'CCAFS SLC-40',
  'Starlink 8 v1.0, SkySats-16, -17, -18, GPS III-03 ',
  15410,
  'LEO',
  'SpaceX, Planet Labs',
  'Success',
  'Success'),
 ('2020-06-30',
  '20:10:46',
  'F9 B5B1060.1',
  'CCAFS SLC-40',
  'GPS III-03, ANASIS-II',
  4311,
  'MEO',
  'U.S. Space Force',
  'Success',
  'Success'),
 ('2020-07-20',
  '21:30:00',
  'F9 B5 B1058.2 ',
  'CCAFS SLC-40',
  'ANASIS-II, Starlink 9 v1.0',
  5500,
  'GTO',
  'Republic of Korea Army, Spaceflight Industries (BlackSky)',
  'Success',
  'Success'),
 ('2020-08-18',
  '14:31:00',
  'F9 B5 B1049.6',
  'CCAFS SLC-40',
  'Starlink 10 v1.0, SkySat-19, -20, -21, SAOCOM 1B ',
  15440,
  'LEO',
  'SpaceX, Planet Labs, PlanetIQ',
  'Success',
  'Success'),
 ('2020-08-30',
  '23:18:00',
  'F9 B5 B1059.4',
  'CCAFS SLC-40',
  'SAOCOM 1B, GNOMES 1, Tyvak-0172',
  3130,
  'SSO',
  'CONAE, PlanetIQ, SpaceX',
  'Success',
  'Success'),
 ('2020-10-24',
  '15:31:34',
  'F9 B5 B1060.3',
  'CCAFS SLC-40',
  'Starlink 14 v1.0, GPS III-04  ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'),
 ('2020-11-05',
  '23:24:23',
  'F9 B5B1062.1',
  'CCAFS SLC-40',
  'GPS III-04 , Crew-1',
  4311,
  'MEO',
  'USSF',
  'Success',
  'Success'),
 ('2020-11-25',
  '2:13:00',
  'F9 B5 B1049.7 ',
  'CCAFS SLC-40',
  'Starlink 15 v1.0, SpaceX CRS-21',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success')]

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [13]:
cur.execute("SELECT SUM(PAYLOAD_MASS__KG_) FROM SPACEXTABLE WHERE CUSTOMER = 'NASA (CRS)'").fetchall()

[(45596,)]

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [14]:
cur.execute("SELECT AVG(PAYLOAD_MASS__KG_) FROM SPACEXTABLE WHERE Booster_Version == 'F9 v1.1'").fetchall()

[(2928.4,)]

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.


_Hint:Use min function_

In [16]:
cur.execute("SELECT Date FROM SPACEXTABLE WHERE Landing_Outcome == 'Success (ground pad)' ORDER BY Date ASC LIMIT 1").fetchall()

[('2015-12-22',)]

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [17]:
cur.execute("SELECT * FROM SPACEXTABLE WHERE Landing_Outcome = 'Success (drone ship)' AND PAYLOAD_MASS__KG_ > 4000 AND PAYLOAD_MASS__KG_ < 6000").fetchall()

[('2016-05-06',
  '5:21:00',
  'F9 FT B1022',
  'CCAFS LC-40',
  'JCSAT-14',
  4696,
  'GTO',
  'SKY Perfect JSAT Group',
  'Success',
  'Success (drone ship)'),
 ('2016-08-14',
  '5:26:00',
  'F9 FT B1026',
  'CCAFS LC-40',
  'JCSAT-16',
  4600,
  'GTO',
  'SKY Perfect JSAT Group',
  'Success',
  'Success (drone ship)'),
 ('2017-03-30',
  '22:27:00',
  'F9 FT  B1021.2',
  'KSC LC-39A',
  'SES-10',
  5300,
  'GTO',
  'SES',
  'Success',
  'Success (drone ship)'),
 ('2017-10-11',
  '22:53:00',
  'F9 FT  B1031.2',
  'KSC LC-39A',
  'SES-11 / EchoStar 105',
  5200,
  'GTO',
  'SES EchoStar',
  'Success',
  'Success (drone ship)')]

### Task 7




##### List the total number of successful and failure mission outcomes

In [19]:
cur.execute("SELECT Mission_Outcome, COUNT(Mission_Outcome) FROM SPACEXTABLE GROUP BY Mission_outcome").fetchall()

[('Failure (in flight)', 1),
 ('Success', 98),
 ('Success ', 1),
 ('Success (payload status unclear)', 1)]

### Task 8



##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [22]:
cur.execute("SELECT DISTINCT(Booster_Version) FROM SPACEXTABLE WHERE PAYLOAD_MASS__KG_ IN (SELECT MAX(PAYLOAD_MASS__KG_) FROM SPACEXTABLE)").fetchall()

[('F9 B5 B1048.4',),
 ('F9 B5 B1049.4',),
 ('F9 B5 B1051.3',),
 ('F9 B5 B1056.4',),
 ('F9 B5 B1048.5',),
 ('F9 B5 B1051.4',),
 ('F9 B5 B1049.5',),
 ('F9 B5 B1060.2 ',),
 ('F9 B5 B1058.3 ',),
 ('F9 B5 B1051.6',),
 ('F9 B5 B1060.3',),
 ('F9 B5 B1049.7 ',)]

### Task 9


##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use  substr(Date, 6,2) as month to get the months and substr(Date,0,5)='2015' for year.**

In [30]:
cur.execute("SELECT SUBSTR(Date, 0, 5), SUBSTR(Date, 6, 2), Booster_Version, Launch_Site, Landing_Outcome FROM SPACEXTABLE WHERE Landing_Outcome LIKE '%drone ship%'").fetchall()

[('2015', '01', 'F9 v1.1 B1012', 'CCAFS LC-40', 'Failure (drone ship)'),
 ('2015', '04', 'F9 v1.1 B1015', 'CCAFS LC-40', 'Failure (drone ship)'),
 ('2015', '06', 'F9 v1.1 B1018', 'CCAFS LC-40', 'Precluded (drone ship)'),
 ('2016', '01', 'F9 v1.1 B1017', 'VAFB SLC-4E', 'Failure (drone ship)'),
 ('2016', '03', 'F9 FT B1020', 'CCAFS LC-40', 'Failure (drone ship)'),
 ('2016', '04', 'F9 FT B1021.1', 'CCAFS LC-40', 'Success (drone ship)'),
 ('2016', '05', 'F9 FT B1022', 'CCAFS LC-40', 'Success (drone ship)'),
 ('2016', '05', 'F9 FT B1023.1', 'CCAFS LC-40', 'Success (drone ship)'),
 ('2016', '06', 'F9 FT B1024', 'CCAFS LC-40', 'Failure (drone ship)'),
 ('2016', '08', 'F9 FT B1026', 'CCAFS LC-40', 'Success (drone ship)'),
 ('2017', '01', 'F9 FT B1029.1', 'VAFB SLC-4E', 'Success (drone ship)'),
 ('2017', '03', 'F9 FT  B1021.2', 'KSC LC-39A', 'Success (drone ship)'),
 ('2017', '06', 'F9 FT  B1029.2', 'KSC LC-39A', 'Success (drone ship)'),
 ('2017', '06', 'F9 FT B1036.1', 'VAFB SLC-4E', 'Success (drone ship)'),
 ('2017', '08', 'F9 FT B1038.1', 'VAFB SLC-4E', 'Success (drone ship)'),
 ('2017', '10', 'F9 B4 B1041.1', 'VAFB SLC-4E', 'Success (drone ship)'),
 ('2017', '10', 'F9 FT  B1031.2', 'KSC LC-39A', 'Success (drone ship)'),
 ('2017', '10', 'F9 B4 B1042.1', 'KSC LC-39A', 'Success (drone ship)'),
 ('2018', '04', 'F9 B4 B1045.1', 'CCAFS SLC-40', 'Success (drone ship)'),
 ('2018', '05', 'F9 B5  B1046.1', 'KSC LC-39A', 'Success (drone ship)')]

### Task 10




##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.

In [26]:
cur.execute("SELECT Landing_Outcome, COUNT(Landing_Outcome) \
            FROM SPACEXTABLE \
            WHERE DATE BETWEEN '2010-06-04' AND '2017-03-20' \
            GROUP BY Landing_Outcome \
            ORDER BY COUNT(Landing_Outcome) DESC").fetchall()

[('No attempt', 10),
 ('Success (drone ship)', 5),
 ('Failure (drone ship)', 5),
 ('Success (ground pad)', 3),
 ('Controlled (ocean)', 3),
 ('Uncontrolled (ocean)', 2),
 ('Failure (parachute)', 2),
 ('Precluded (drone ship)', 1)]

### Reference Links

* <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>  

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*  <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

## Change log
| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>